# -*- coding: utf-8 -*-
"""walmart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnRqCmhv97dkzysMSDz4sRpCbm7FYFwu
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_csv('https://raw.githubusercontent.com/AKHILKRISHNA-2004/Dataset/refs/heads/main/Walmart.csv')
df.head()

"""**DATA PREPARATION**"""

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['DayOfweek'] = df['Date'].dt.dayofweek

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'

df['Season'] = df['Month'].apply(get_season)

df.isnull().sum()

df.duplicated().sum()

df.head()

len(df)

df.info()

df.describe()

df.drop(df[df['Year']==2012].index, inplace=True)
#since the data with the year 2012 contains only fewer data compared to 2010 and 2011. All the data with year 2012 is deleted to avoid misinterpretations of results

len(df)

df.to_csv("Walmart_Preprocessed.csv", index=False)
from google.colab import files
files.download("Walmart_Preprocessed.csv")

"""**EDA**"""

df.corr(numeric_only = True)["Weekly_Sales"]

"""
  we can infer from here that if the store is large then there will be increase in weekley sales,
  because when store is more it means the store can have lot more products,which result lot more customer attraction and obviously higher sales
"""

#histplot
plt.figure(figsize = (8,5))
sns.histplot(df['Weekly_Sales'], bins=50, kde = True)
plt.title("Distribution of Weekly Sales")
plt.show()

plt.figure(figsize=(12,6))
df.groupby('Store')['Weekly_Sales'].mean().plot(kind='bar', color='teal')
plt.title("Average Weekly Sales by Store")
plt.ylabel("Average Sales")
plt.show()

store_sales = df.groupby('Store')['Weekly_Sales'].mean().sort_values(ascending=False)
print("Top 5 Stores:\n", store_sales.head())
print("\nBottom 5 Stores:\n", store_sales.tail())
#performance of stores

plt.figure(figsize=(8,5))
df.groupby('Month')['Weekly_Sales'].mean().plot(kind='bar', color='orange')
plt.title("Average Monthly Sales")
plt.show()

plt.figure(figsize=(6,4))
df.groupby('Holiday_Flag')['Weekly_Sales'].mean().plot(kind='bar', color=['skyblue','salmon'])
plt.title("Average Sales: Holiday vs Non-Holiday")
plt.xticks([0,1], ["Non-Holiday","Holiday"], rotation=0)
plt.ylabel("Average Weekly Sales")
plt.show()

df.corr(numeric_only=True)['Temperature']

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
df.groupby('Date')['Weekly_Sales'].sum().plot()
holiday_weeks = df[df['Holiday_Flag']==1].groupby('Date')['Weekly_Sales'].sum()
plt.scatter(holiday_weeks.index, holiday_weeks.values, color='red', label='Holiday Weeks')
plt.title("Weekly Sales Trend with Holiday Highlights")
plt.ylabel("Total Sales")
plt.legend()
plt.show()

fig2 = px.treemap(
    df,
    path=['Store', 'Month'],
    values='Weekly_Sales',
    color='Weekly_Sales',
    color_continuous_scale='Greens',
    title="Treemap of Store & Month-wise Weekly Sales"
)
fig2.show()

df.corr(numeric_only = True)["Fuel_Price"]
#positive coorelation with Year that means fuel price increases when year increase

# Define features with higher correlation
features = ["Year"]

plt.figure(figsize=(15, 4))

for i, col in enumerate(features, 1):
    plt.subplot(1, 3, i)
    sns.scatterplot(x=df[col], y=df["Fuel_Price"], alpha=0.5)
    sns.regplot(x=df[col], y=df["Fuel_Price"], scatter=False, color="red")  # add trend line
    plt.title(f"Fuel_Price vs {col}")

plt.tight_layout()
plt.show()

'''
#fuel vs year
  *Fuel prices steadily increased over the years
  *correlatoin is 0.84 which is pretty high
'''

df.corr(numeric_only=True)['CPI']
# comparitevely strong negative correlation with UNEMPLOYMENT
''' according to phillips curve it means that
1. when unemployment is low it means more people work, that means more people earn with tends to increase consumer spending natrually when demand is more price increases
   when price increases inflation increase
2. when unemployment is high it means less people work, that means less consumer spending which lowers the price of goods and services that puts downward pressure on
   prices, leading to lower inflation
'''

sns.scatterplot(x = df['CPI'], y = df['Unemployment'], alpha = 0.5)
sns.regplot(x = df['CPI'], y = df['Unemployment'], scatter = False, color = 'red')
plt.title("CPI vs Unemployment")
plt.plot()
'''
  a slight negative trend between CPI vs Unemployment that says that when CPI is incresed there is decrease in the unemployment rate,
  this is explained by phillips curve
'''

df.corr(numeric_only=True)['Unemployment']
#correlation similar to that of correlation of CPI

df.corr(numeric_only=True)['Store']

# Pick a few stores for comparison
selected_stores = df[df['Store'].isin([20,14,4,12,2,3,38,5,44,33])]

# Aggregate features per store
agg = selected_stores.groupby('Store')[['Weekly_Sales','Fuel_Price','CPI','Unemployment','Temperature']].mean().reset_index()

# Normalize values (so radar chart makes sense)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = pd.DataFrame(scaler.fit_transform(agg.iloc[:,1:]), columns=agg.columns[1:])
scaled['Store'] = agg['Store']

# Melt to long format for radar plot
melted = scaled.melt(id_vars='Store')

fig = px.line_polar(
    melted,
    r='value',
    theta='variable',
    color='Store',
    line_close=True,
    title="Radar Chart: Store Comparison Across Features"
)
fig.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Extract month and year
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month

# Pivot table: average sales per store per month
sales_pivot = df.pivot_table(
    index='Store',
    columns='Month',
    values='Weekly_Sales',
    aggfunc='mean'
)

# Plot heatmap
plt.figure(figsize=(14,8))
sns.heatmap(sales_pivot, cmap="YlGnBu", annot=False, cbar_kws={'label': 'Avg Weekly Sales'})
plt.title("Heatmap of Average Monthly Sales by Store")
plt.ylabel("Store")
plt.xlabel("Month")
plt.show()

#scatterplot
fig = px.scatter(
    df,
    x="Temperature",
    y="Weekly_Sales",
    opacity=0.5,
    title="Weekly Sales vs Temperature",
    labels={"Temperature": "Temperature (°F)", "Weekly_Sales": "Weekly Sales"},
)

fig.show()

fig = px.scatter(
    df,
    x="Fuel_Price",
    y="Weekly_Sales",
    opacity=0.5,
    title="Weekly Sales vs Fuel Price",
    labels={"Fuel_Price": "Fuel Price ($)", "Weekly_Sales": "Weekly Sales"}
)

fig.show()

plt.figure(figsize=(8,6))
sns.heatmap(df[['Weekly_Sales','Temperature','Fuel_Price','CPI','Unemployment']].corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

fig2 = px.treemap(
    df,
    path=['Store', 'Temperature'],
    values='Weekly_Sales',
    color='Weekly_Sales',
    color_continuous_scale='Greens',
    title="Treemap of Store & Month-wise Weekly Sales"
)
fig2.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.scatterplot(
    x=df["Temperature"],
    y=df["Fuel_Price"],
    size=df["Weekly_Sales"],   # bubble size = Weekly Sales
    hue=df["Store"],           # color = Store
    alpha=0.6,
    palette="tab10"
)

plt.title("Weekly Sales relation with Temperature and Fuel Price (by Store)")
plt.xlabel("Temperature")
plt.ylabel("Fuel Price")
plt.legend(bbox_to_anchor=(1.05, 1), loc=2)
plt.show()

import csv
import random
from datetime import datetime, timedelta

locations = ["Jakarta", "Bali", "Surabaya", "Bandung", "Medan"]
num_taxpayers = 100
filename = "synthetic_tax_data.csv"

with open(filename, "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["taxpayer_id","transaction_id","amount","location","timestamp"])

    for t in range(1, num_taxpayers+1):
        taxpayer_id = f"T{t:03d}"
        num_tx = random.randint(5, 10)
        for tx in range(1, num_tx+1):
            transaction_id = f"tx{tx:03d}"
            # Amount: mostly small, some high for suspicious cases
            if random.random() < 0.1:
                amount = random.randint(50000, 200000)  # suspicious high
            else:
                amount = round(random.uniform(1.0, 10000.0), 2)
            location = random.choice(locations)
            timestamp = (datetime(2025,6,1,8,0,0) + timedelta(hours=random.randint(0,200))).isoformat()
            writer.writerow([taxpayer_id, transaction_id, amount, location, timestamp])

print(f"Synthetic dataset generated: {filename}")

df.to_csv("synthetic_tax_data.csv", index=False)
from google.colab import files
files.download("synthetic_tax_data.csv")